name: QuantumCreations
favicon: null
layout_spectrum: 0.1366069803480059
typography_spectrum: 0.8703901241533458
title: 'Sparkles, sounds, movement combined together'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ededeb'
    - '#fe0000'
    - '#fe4f00'
    - '#14162b'
    - '#a1a3a0'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.14321582508273423
  rhythmicContrast: 0.75
purpose: []
